# Generated by Django 4.2.6 on 2024-04-18 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название медитации')),
                ('audio', models.FileField(upload_to='uploads/meditations/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'ogg', 'aac'])], verbose_name='Запись медитации')),
                ('duration', models.DurationField(blank=True, max_length=50, null=True, verbose_name='Длительность')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум?')),
            ],
        ),
    ]
