# Generated by Django 4.2.6 on 2024-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Длительность'),
        ),
    ]
