# Generated by Django 4.2.6 on 2024-04-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditation', '0002_alter_meditation_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditation',
            options={'verbose_name': 'Медитация', 'verbose_name_plural': 'Медитации'},
        ),
        migrations.CreateModel(
            name='MetaphoricalСards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_card', models.ImageField(upload_to='images/metaphorical_cards/', verbose_name='Изображение карты')),
                ('value', models.TextField(verbose_name='Значение')),
                ('transcript', models.TextField(verbose_name='Расшифровка')),
                ('advice', models.TextField(verbose_name='Совет')),
                ('affirmation', models.TextField(verbose_name='Аффермация')),
                ('likes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Метофарическая карта',
                'verbose_name_plural': 'Метофарические карты',
            },
        ),
    ]
