# Generated by Django 4.2.6 on 2024-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_alter_meditation_options_metaphoricalсards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.URLField(verbose_name='ссылка на соц.сеть Вконтакте')),
                ('instagram', models.URLField(verbose_name='ссылка на соц.сеть инстаграм')),
                ('telegram', models.URLField(verbose_name='Телеграм')),
                ('yandex_dzen', models.URLField(verbose_name='Яндекс дзен')),
                ('website', models.URLField(verbose_name='Вебсайт')),
            ],
            options={
                'verbose_name': 'Контакт приложения',
                'verbose_name_plural': 'Контакты приложения',
            },
        ),
    ]
