# Generated by Django 4.2.6 on 2024-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0006_alter_metaphoricalсards_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaphoricalсards',
            name='image_card',
            field=models.ImageField(blank=True, null=True, upload_to='images/metaphorical_cards/', verbose_name='Изображение карты'),
        ),
    ]
