# Generated by Django 4.2.6 on 2024-05-14 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditation', '0007_alter_metaphoricalсards_image_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='likes',
            field=models.ManyToManyField(related_name='meditation_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
