# Generated by Django 4.2.6 on 2024-05-14 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditation', '0008_meditation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='meditation_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
