# Generated by Django 4.2.6 on 2024-05-14 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0009_alter_meditation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/meditations/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'ogg', 'aac'])], verbose_name='Запись медитации'),
        ),
    ]
