# Generated by Django 4.2.6 on 2024-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0010_alter_meditation_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='is_bronze',
            field=models.BooleanField(default=False, verbose_name='Бронза?'),
        ),
        migrations.AddField(
            model_name='meditation',
            name='is_silver',
            field=models.BooleanField(default=False, verbose_name='Серебро?'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Золото?'),
        ),
    ]
