# Generated by Django 4.2.6 on 2024-05-20 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditation', '0011_meditation_is_bronze_meditation_is_silver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaphoricalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_card', models.ImageField(blank=True, null=True, upload_to='images/metaphorical_cards/', verbose_name='Изображение карты')),
                ('video', models.FileField(upload_to='videos/metaphorical_cards/', verbose_name='Видео')),
                ('meaning', models.TextField(verbose_name='Значение')),
                ('transcript', models.TextField(verbose_name='Расшифровка')),
                ('advice', models.TextField(verbose_name='Совет')),
                ('affirmation', models.TextField(verbose_name='Аффермация')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='like_user', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Колода метафорических карт',
                'verbose_name_plural': 'Колода метафорических карт',
            },
        ),
        migrations.CreateModel(
            name='MoneyMetaphoricalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/money_cards/', verbose_name='Фото')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('meaning', models.TextField(verbose_name='Значение')),
                ('advice', models.TextField(verbose_name='Совет')),
                ('affirmation', models.TextField(verbose_name='Аффермация')),
            ],
            options={
                'verbose_name': 'Денежная колода метафорических карт',
                'verbose_name_plural': 'Денежная колода метафорических карт',
            },
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='is_bronze',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='is_silver',
        ),
        migrations.DeleteModel(
            name='MetaphoricalСards',
        ),
    ]
