# Generated by Django 4.2.6 on 2024-05-03 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='8G3G0G1', editable=False, max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('d0e25711-684f-434d-96c6-aa9b75b97ed7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
