# Generated by Django 4.2.6 on 2024-05-16 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='5I3I7I9', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('7f842e92-9e30-49eb-8f2a-6b65912d1e3d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
