# Generated by Django 4.2.6 on 2024-04-11 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_esuser_is_verified_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('122a8034-f55b-4d2b-a20f-17da9202fe93'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
