# Generated by Django 4.2.6 on 2024-05-03 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='1S3S6S3', editable=False, max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('825bbd73-3df3-41c4-95ab-9c58f294c975'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
