# Generated by Django 4.2.6 on 2024-05-20 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='esuser',
            name='is_purchased_money_metaphorical_cards',
            field=models.BooleanField(default=False, verbose_name='Оплата за метафорические карты'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='8N6N4N9', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('000e6f42-e9f4-4a50-90cb-e9571d7aa950'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
