# Generated by Django 4.2.6 on 2024-04-15 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('d812d587-9d98-4cf2-b920-e805ac168f1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
