# Generated by Django 4.2.6 on 2024-04-18 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('a2599655-f0f4-44a4-b407-518b0592ecec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
