# Generated by Django 4.2.6 on 2024-04-29 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('5c997da5-47b5-405a-a7a2-e38639ca359e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
