# Generated by Django 4.2.6 on 2024-05-03 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('525d1671-762d-4f21-a0b5-c49a8bc7364a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
