# Generated by Django 4.2.6 on 2024-05-06 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='7U4U4U5', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('3d89f134-2971-4c24-bdeb-2e7e3ff38056'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
