# Generated by Django 4.2.6 on 2024-05-06 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='2G3G3G2', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('fed40918-1f0e-4ea9-a1b5-aee1edaf7455'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
