# Generated by Django 4.2.6 on 2024-05-09 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='9M1M4M6', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('26ca0c41-60ca-4a3a-a875-ed7e9bd167ff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
