# Generated by Django 4.2.6 on 2024-05-09 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='3F0F3F5', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('5c772bfd-f435-43a1-9b2a-59b0621e9541'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
