# Generated by Django 4.2.6 on 2024-05-09 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='3X4X4X9', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('dd1d3a71-697c-442b-81e7-79e50a1d83eb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
