# Generated by Django 4.2.6 on 2024-05-14 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='4R6R6R8', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('4c6a5748-7bc2-430f-8666-36819fb1c8f4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
