# Generated by Django 4.2.6 on 2024-05-14 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='esuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум?'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='8I8I9I6', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('36bb67ca-d8a9-4d74-8d19-be2388bc3e47'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
