# Generated by Django 4.2.6 on 2024-05-14 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_esuser_promocode_alter_esuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='promocode',
            field=models.CharField(default='2M1M4M6', max_length=10, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('9438ed74-f23e-43f2-b359-b3a92212bc99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
