# Generated by Django 4.2.6 on 2024-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('quote', models.CharField(blank=True, max_length=70, null=True, verbose_name='Цитата снизу')),
                ('preority', models.BooleanField(default=True, verbose_name='Выставить в приоритет?')),
                ('image', models.ImageField(upload_to='images/ads/', verbose_name='Баннер')),
            ],
        ),
    ]
