# Generated by Django 4.2.6 on 2024-04-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admodel',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
    ]
