# Generated by Django 4.2.6 on 2024-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('IN PROCCESING', 'IN PROCCESESING')], default='IN PROCCESING', max_length=120, verbose_name='Статус'),
        ),
    ]
