# Generated by Django 4.2.6 on 2024-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='В рублях ₽', max_digits=10, verbose_name='Стоимость'),
        ),
    ]
