# Generated by Django 4.2.6 on 2024-05-09 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_package_price_alter_package_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_uuid',
            field=models.UUIDField(default=uuid.UUID('cde81b5e-da3a-4c43-87da-d0591abfabf1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
