# Generated by Django 4.2.6 on 2024-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_payment_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uuid',
            field=models.CharField(editable=False, max_length=240, primary_key=True, serialize=False),
        ),
    ]
