# Generated by Django 4.2.6 on 2024-05-09 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_payment_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uuid',
            field=models.UUIDField(default=uuid.UUID('885d8860-7e66-4a87-833c-2a80f0a9d8fd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
