# Generated by Django 4.2.6 on 2024-05-09 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_payment_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uuid',
            field=models.UUIDField(default=uuid.UUID('cf49790c-5b9f-4296-b349-318049268101'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
