# Generated by Django 4.2.6 on 2024-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_remove_payment_id_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(editable=False, max_length=120, verbose_name='Статус'),
        ),
    ]
